server:
  port: 8081

spring:
  application:
    name: products
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/products_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:products}
    password: ${DB_PASSWORD:products123}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  build:
    version: ${APP_BUILD_VERSION:0.0.1-SNAPSHOT}
  contact:
    name: ${APP_CONTACT_NAME:}
    email: ${APP_CONTACT_EMAIL:}
    url: ${APP_CONTACT_URL:}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
